import { NextRequest, NextResponse } from "next/server";
import { Listing, HousingType, HousingForm } from "@/types";

// Mock DB — replace with real data from scraper
const MOCK_LISTINGS: Record<string, Listing> = {
  "1": {
    id: "1",
    title: "Vacker 3:a i Majorna med havsutsikt",
    address: "Stigbergsliden 12",
    neighborhood: "Majorna",
    city: "Göteborg",
    postalCode: "414 71",
    price: 2850000,
    monthlyFee: 4200,
    size: 78,
    rooms: 3,
    floor: "3",
    housingType: HousingType.Apartment,
    housingForm: HousingForm.Condominium,
    constructionYear: 1925,
    renovationYear: 2019,
    imageUrl: "",
    images: [],
    description: "Vacker trea i charmiga Majorna med fantastisk havsutsikt. Renoverat kök och badrum 2019. Bästa läget i Göteborg med nära till både havet och stan. Hela 78 kvm med generösa rum och hög takhöjd.",
    amenities: ["Balkong", "Hiss", "Förråd", "Tvättstuga"],
    publishedAt: "2026-04-18T10:00:00Z",
    url: "https://example.com/1",
    broker: { name: "Anna Svensson", phone: "070-1234567", email: "anna@exempel.se", company: "Mäklarfirman AB" },
    aiScore: 82,
    aiTags: ["Havsutsikt", "Majorna", "Renoverad"],
    aiSummary: "Fantastisk trea i ett av Göteborgs mest eftertraktade områden. Havsutsikt och nyligen renoverat kök/badrum ger hög livskvalitet. Pris per m² är något över snittet för Majorna men motiveras av utsikten och skicket.",
  },
  "2": {
    id: "2",
    title: "Modern studio i centralt läge",
    address: "Kungsportsplatsen 5",
    neighborhood: "Centrum",
    city: "Göteborg",
    postalCode: "411 03",
    price: 1950000,
    monthlyFee: 3100,
    size: 32,
    rooms: 1,
    floor: "5",
    housingType: HousingType.Studio,
    housingForm: HousingForm.Condominium,
    constructionYear: 2018,
    imageUrl: "",
    images: [],
    description: "Modern och fin etta i nyproduktion mitt i stan. Öppen planlösning med smakfulla materialval. Närhet till allt.",
    amenities: ["Hiss", "P-plats", "Cykelförråd"],
    publishedAt: "2026-04-19T08:00:00Z",
    url: "https://example.com/2",
    broker: { name: "Erik Johansson", company: "Svensk Fastighetsförmedling" },
    aiScore: 71,
    aiTags: ["Nyproduktion", "Centrum", "Etta"],
  },
  "3": {
    id: "3",
    title: "Familjevilla i Askim med trädgård",
    address: "Askimsbacken 22",
    neighborhood: "Askim",
    city: "Göteborg",
    postalCode: "436 31",
    price: 6450000,
    size: 165,
    rooms: 6,
    housingType: HousingType.House,
    housingForm: HousingForm.TenantOwnership,
    constructionYear: 1992,
    renovationYear: 2021,
    imageUrl: "",
    images: [],
    description: "Underbar villa i Askim med stor trädgård och uteplatser. Perfekt för familjen med 6 rum och generösa ytor. Renoverad 2021 med nytt kök och badrum. Garage och carport.",
    amenities: ["Trädgård", "Garage", "Uterum", "Öppen spis"],
    publishedAt: "2026-04-20T14:00:00Z",
    url: "https://example.com/3",
    broker: { name: "Maria Lind", phone: "031-987654", email: "maria@exempel.se", company: "Länsförsäkringar Fastighetsförmedling" },
    aiScore: 88,
    aiTags: ["Villa", "Trädgård", "Askim", "Familj"],
  },
  "4": {
    id: "4",
    title: "Charmig 2:a i Linné — ompossible",
    address: "Linnégatan 45",
    neighborhood: "Linné",
    city: "Göteborg",
    postalCode: "413 04",
    price: 2200000,
    monthlyFee: 3800,
    size: 55,
    rooms: 2,
    floor: "2",
    housingType: HousingType.Apartment,
    housingForm: HousingForm.Condominium,
    constructionYear: 1938,
    imageUrl: "",
    images: [],
    description: "Charmig tvåa i Linné med originaldetaljer. Bra planlösning med potential att öppna upp köket. Nära Linnéplatsen och all stadsliv.",
    amenities: ["Balkong", "Förråd"],
    publishedAt: "2026-04-21T09:30:00Z",
    url: "https://example.com/4",
    broker: { name: "Johan Berg", company: "Fastighetsbyrån" },
    aiScore: 65,
    aiTags: ["Linné", "Ompossible", "Charmig"],
  },
};

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const listing = MOCK_LISTINGS[id];

  if (!listing) {
    return NextResponse.json({ error: "Listing not found" }, { status: 404 });
  }

  return NextResponse.json(listing);
}